version: "3.7"
services:
  # POSTGRES SERVER
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: pslist-database
      POSTGRES_PASSWORD: postgres-container
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
# REDE
networks:
  dev-network:
    driver: bridge